package evento;
        
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

public class SignUp extends javax.swing.JFrame {


    /** Creates new form SignUp
 */
    public SignUp() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SidePanel = new javax.swing.JPanel();
        EventoLabel = new javax.swing.JLabel();
        EventoIconLabel = new javax.swing.JLabel();
        SignUp = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        confirmPasswordLabel = new javax.swing.JLabel();
        passwordText = new javax.swing.JPasswordField();
        SignInButton = new javax.swing.JButton();
        passwordLabel = new javax.swing.JLabel();
        surnameLabel = new javax.swing.JLabel();
        surnameText = new javax.swing.JTextField();
        nameText = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        usernameText = new javax.swing.JTextField();
        confirmPasswordText = new javax.swing.JPasswordField();
        SignUpInvit = new javax.swing.JLabel();
        SignUpButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1138, 607));
        setResizable(false);

        SidePanel.setBackground(new java.awt.Color(0, 0, 123));

        EventoLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        EventoLabel.setForeground(new java.awt.Color(255, 255, 255));
        EventoLabel.setText("Evento");

        EventoIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/evento/assets/eventoIcon.png"))); // NOI18N

        org.jdesktop.layout.GroupLayout SidePanelLayout = new org.jdesktop.layout.GroupLayout(SidePanel);
        SidePanel.setLayout(SidePanelLayout);
        SidePanelLayout.setHorizontalGroup(
            SidePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(SidePanelLayout.createSequentialGroup()
                .add(26, 26, 26)
                .add(EventoIconLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(EventoLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        SidePanelLayout.setVerticalGroup(
            SidePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(SidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(SidePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(EventoLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(EventoIconLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SignUp.setBackground(new java.awt.Color(204, 204, 235));

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nameLabel.setText("Name");

        confirmPasswordLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        confirmPasswordLabel.setText("Confirm Password");

        passwordText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        SignInButton.setBackground(new java.awt.Color(0, 0, 123));
        SignInButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        SignInButton.setForeground(new java.awt.Color(255, 255, 255));
        SignInButton.setText("SIGN UP");
        SignInButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignInButtonMouseClicked(evt);
            }
        });

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        passwordLabel.setText("Password");

        surnameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        surnameLabel.setText("Surname");

        surnameText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        nameText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        usernameLabel.setText("Username");

        usernameText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        confirmPasswordText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        org.jdesktop.layout.GroupLayout SignUpLayout = new org.jdesktop.layout.GroupLayout(SignUp);
        SignUp.setLayout(SignUpLayout);
        SignUpLayout.setHorizontalGroup(
            SignUpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(SignUpLayout.createSequentialGroup()
                .add(20, 20, 20)
                .add(SignUpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(nameLabel)
                    .add(usernameLabel)
                    .add(confirmPasswordLabel)
                    .add(surnameLabel)
                    .add(passwordLabel))
                .add(23, 23, 23)
                .add(SignUpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(nameText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .add(surnameText)
                    .add(passwordText)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, usernameText)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, confirmPasswordText))
                .add(55, 55, 55))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, SignUpLayout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(SignInButton)
                .add(109, 109, 109))
        );
        SignUpLayout.setVerticalGroup(
            SignUpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(SignUpLayout.createSequentialGroup()
                .add(24, 24, 24)
                .add(SignUpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nameLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(nameText))
                .add(30, 30, 30)
                .add(SignUpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(surnameLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(surnameText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(31, 31, 31)
                .add(SignUpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(usernameLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(usernameText))
                .add(30, 30, 30)
                .add(SignUpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(passwordLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(passwordText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30)
                .add(SignUpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(confirmPasswordLabel)
                    .add(confirmPasswordText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30)
                .add(SignInButton)
                .add(36, 36, 36))
        );

        SignUpInvit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SignUpInvit.setText("Already have an account  ?");

        SignUpButton.setBackground(new java.awt.Color(204, 204, 235));
        SignUpButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        SignUpButton.setForeground(new java.awt.Color(0, 0, 123));
        SignUpButton.setText("SIGN IN");
        SignUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpButtonMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(SidePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(268, 268, 268)
                        .add(SignUpInvit)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(SignUpButton)
                        .add(269, 269, 269))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(SignUp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(169, 169, 169))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(SidePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .add(SignUp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(SignUpInvit)
                    .add(SignUpButton))
                .add(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Action listener to go to sign in  window 
    private void SignUpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpButtonMouseClicked
        SignUp.super.dispose();
        SignIn Si = new SignIn();
        Si.setVisible(true);
    }//GEN-LAST:event_SignUpButtonMouseClicked
    
    // Action listener to call validate_sign_up() method
    private void SignInButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignInButtonMouseClicked
        if (validateSignupForm()== true){
            DatabaseConnection db = new DatabaseConnection();
            User us = new User(
                nameText.getText(),
                surnameText.getText(),
                usernameText.getText(),
                passwordText.getText()
            );
            try {
                db.setData(us);  
                db.printUserData();
                JOptionPane.showMessageDialog(null, "You signed up successfully !\nYou can now sign in to Evento");
                SignUp.super.dispose();
                SignIn s = new SignIn();
                s.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_SignInButtonMouseClicked
    
    // Method to validate my sign up form and store data temporally in a array
    public boolean validateSignupForm(){
        boolean b ;
        
        if (nameText.getText().isEmpty() && surnameText.getText().isEmpty() && usernameText.getText().isEmpty() && passwordText.getText().isEmpty() && confirmPasswordText.getText().isEmpty()){
            b = false;
            JOptionPane.showMessageDialog(null,"Please fill your informations to go");
            nameText.requestFocus();
        }
        else if (nameText.getText().isEmpty() || surnameText.getText().isEmpty() || usernameText.getText().isEmpty() || passwordText.getText().isEmpty() || confirmPasswordText.getText().isEmpty()){
            b = false;
            JOptionPane.showMessageDialog(null,"1 or some fiels are empty !\nPlease fill all the fields ");
            nameText.requestFocus();
        }         
        else{
            if (!isValidPassword(passwordText.getText())){
                b = false;
                JOptionPane.showMessageDialog(null,"Weak password ! \nHere the requirements :\nPassword must be at least 6 characters\nPassword must contain at least 1 letter, 2 digit and 1 special character as @#$%^&+= \nE.g: @axel77");
                passwordText.setText("");
                confirmPasswordText.setText("");
                passwordText.requestFocus();
            }
            else if (!(passwordText.getText().equals(confirmPasswordText.getText()))){
                b = false;
                JOptionPane.showMessageDialog(null, "Confirm password doesn't match with the given password ! \nPlease check");
                confirmPasswordText.setText("");
                confirmPasswordText.requestFocus();

            }
            else{ 
                b = true;
            }  
        }
        return b;
    }

    // Method to check the password validity using a regular expression 
    public boolean isValidPassword(String password){
        String regex = "^(?=.*[a-zA-Z])(?=.*\\d.*\\d)(?=.*[@#$%^&+=]).{6,}$";
        Pattern pattern =Pattern.compile(regex); 
        Matcher matcher = pattern.matcher(password);
        return matcher.matches();
    }
    
    //Method to clear the content 



    public static void main(String args[]){     
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    public JTextField getNameText() {
        return nameText;
    }

    public JPasswordField getPasswordText() {
        return passwordText;
    }

    public JTextField getSurnameText() {
        return surnameText;
    }

    public JTextField getUsernameText() {
        return usernameText;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EventoIconLabel;
    private javax.swing.JLabel EventoLabel;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JButton SignInButton;
    private javax.swing.JPanel SignUp;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JLabel SignUpInvit;
    private javax.swing.JLabel confirmPasswordLabel;
    private javax.swing.JPasswordField confirmPasswordText;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JLabel surnameLabel;
    private javax.swing.JTextField surnameText;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables

}
